/**
@file
*/

#ifndef PREP_STMS_H_
#define PREP_STMS_H_


int stmtAddAll(
    dbconn * conn);

void stmtDeleteAll(
    dbconn * conn);

// Note: keep in sync with array in implementation file
enum prep_stmts_rtr {
    DB_PSTMT_RTR_GET_SESSION,
    DB_PSTMT_RTR_GET_LATEST_SERNUM,
    DB_PSTMT_RTR_HAS_ROWS_RTR_UPDATE,
    DB_PSTMT_RTR_READ_SER_NUM_AS_PREV,
    DB_PSTMT_RTR_READ_SER_NUM_AS_CURRENT,
    DB_PSTMT_RTR_SERIAL_QRY_GET_NEXT,
    DB_PSTMT_RTR_RESET_QRY_GET_NEXT,
    DB_PSTMT_RTR_COUNT_SESSION,
    DB_PSTMT_RTR_DELETE_INCOMPLETE_INCREMENTAL,
    DB_PSTMT_RTR_DELETE_INCOMPLETE_FULL,
    DB_PSTMT_RTR_DETECT_INCONSISTENT_STATE,
    DB_PSTMT_RTR_INSERT_FULL,
    DB_PSTMT_RTR_INSERT_INCREMENTAL,
    DB_PSTMT_RTR_HAS_CHANGES,
    DB_PSTMT_RTR_INSERT_UPDATE,
    DB_PSTMT_RTR_DELETE_USELESS_FULL,
    DB_PSTMT_RTR_IGNORE_OLD_FULL,
    DB_PSTMT_RTR_DELETE_OLD_FULL,
    DB_PSTMT_RTR_DELETE_OLD_UPDATE,
    DB_PSTMT_RTR_IGNORE_OLD_INCREMENTAL,
    DB_PSTMT_RTR_DELETE_OLD_INCREMENTAL,
};

enum prep_stmts_chaser {
    DB_PSTMT_CHASER_GET_TIME,
    DB_PSTMT_CHASER_GET_CRLDP,
    DB_PSTMT_CHASER_GET_SIA,
    DB_PSTMT_CHASER_GET_AIA
};


#endif                          // PREP_STMS_H_
