-- $Id$ --
--
-- ***** BEGIN LICENSE BLOCK *****
-- 
-- BBN Rule Editor/Engine for Address and AS Number PKI
-- Verison 1.0
-- 
-- US government users are permitted unrestricted rights as
-- defined in the FAR.  
--
-- This software is distributed on an "AS IS" basis, WITHOUT
-- WARRANTY OF ANY KIND, either express or implied.
--
-- Copyright (C) BBN Technologies 2007.  All Rights Reserved.
--
-- Contributor(s):  Charles Gardiner
--
-- ***** END LICENSE BLOCK *****
--

DEFINITIONS ::=

PrivateKey ::= SEQUENCE
  {
  v INTEGER,
  n INTEGER,
  e INTEGER,
  d INTEGER,
  p INTEGER,
  q INTEGER,
  e1 INTEGER,
  e2 INTEGER,
  u INTEGER
  }
