#!/bin/sh

# set environment variables if not set
THIS_SCRIPT_DIR=$(dirname $(which $0))
. $THIS_SCRIPT_DIR/../envir.setup

# run test 2
# checks: garbage collection sets status of certs to unknown

echo ""
echo "Running test 2"
$RPKI_ROOT/proto/garbage
echo "Should be 5 entries (unknown = valid):"
$RPKI_ROOT/proto/query -t cert -d ski -v
