#!/bin/sh

# set environment variables if not set
THIS_SCRIPT_DIR=$(dirname $(which $0))
. $THIS_SCRIPT_DIR/../envir.setup

# run test 1
# checks: validating certs, both in order and out of order
# checks: revoking certs based on crl: both in order and out of order

echo ""
echo "Running test 1"
$RPKI_ROOT/rsync_aur/rsync_aur -s -t $RPKI_PORT -f $RPKI_ROOT/testing/testAdd -d $RPKI_ROOT/testing/REPOSITORY
echo "Should be 5 entries (no validity check):"
$RPKI_ROOT/proto/query -t cert -d ski
echo "Should be 5 entries (validity check):"
$RPKI_ROOT/proto/query -t cert -d ski -v
