#!/bin/sh

# set environment variables if not set
THIS_SCRIPT_DIR=$(dirname $(which $0))
. $THIS_SCRIPT_DIR/../envir.setup

# run test for duplicates, same as test 1 except with duplicate certs and crls

echo ""
echo "Running test duplicates"
$RPKI_ROOT/rsync_aur/rsync_aur -s -t $RPKI_PORT -f $RPKI_ROOT/testing/testDup -d $RPKI_ROOT/testing/REPOSITORY
echo "Should be 5 entries (no validity check):"
$RPKI_ROOT/proto/query -t cert -d ski
echo "Should be 5 entries (validity check):"
$RPKI_ROOT/proto/query -t cert -d ski -v
echo "Should be 1 entries (crls):"
$RPKI_ROOT/proto/query -t crl -d aki
echo "Should be 1 entries (roas):"
$RPKI_ROOT/proto/query -t roa -d ski
