#!/bin/sh

echo "delete from apki_cert where ski=\"D3:64:16:F7:4F:6F:2E:53:7B:84:42:0D:9B:72:2F:E8:CB:58:0B:4C\";" | mysql $RPKI_DB -u mysql
echo "delete from apki_cert where ski=\"B4:4D:ED:FD:28:98:01:6E:41:18:30:25:66:A1:6C:C5:B5:BA:CD:75\";" | mysql $RPKI_DB -u mysql
echo "delete from apki_roa;" | mysql $RPKI_DB -u mysql

${RPKI_ROOT}/rsync_aur/rsync_aur -t ${RPKI_PORT} -d ${RPKI_ROOT}/performance/REPOSITORY -f ${RPKI_ROOT}/performance/roaAdd > roa_output

echo "update apki_cert set flags=4;" | mysql $RPKI_DB -u mysql

start=`date +%s`

${RPKI_ROOT}/rsync_aur/rsync_aur -s -t ${RPKI_PORT} -d ${RPKI_ROOT}/performance/REPOSITORY -f ${RPKI_ROOT}/performance/roaAdd2 >> roa_output

end=`date +%s`
echo "load required $(($end-$start)) seconds" >> roa_output
