#!/bin/sh

# set environment variables if not set
THIS_SCRIPT_DIR=$(dirname $0)
. $THIS_SCRIPT_DIR/../envir.setup

echo About to clear database $RPKI_DB ...

# set up an initial database
$RPKI_ROOT/proto/rcli -x -t $RPKI_ROOT/performance/REPOSITORY -y
