.TH GEN_KEY 1 "2010 Feb 2" "ASN.1 Tools" "ROA-PKI"

.SH NAME
gen_key \- generates an RSA key pair of specified size

.SH SYNOPSIS
.B gen_key 
.I filename size

.SH DESCRIPTION
Generates an RSA key pair with a public modulus of \fIsize\fP bits.
Results are written to to \fIfilename\fP as a cryptlib keyfile (".p15")
with label "label" and password "password".
.PP
Response messages:
.IP
Usage: filename keysize in bits
.IP
Making ... with key size ... bits
.IP
Invalid key size
.PP
where the ellipsis is replaced with specific information.

.SH AUTHOR
Charlie Gardiner.
