.TH MAKE_OIDTABLE 1 "2010 Feb 9" "ASN.1 Tools" "ROA-PKI"

.SH NAME
make_oidtable \- makes a table of ASN.1 object identifiers (OIDs)

.SH SYNOPSIS
.B make_oidtable
.I tablefile file.h ...

.SH DESCRIPTION
This program makes a table of OBJECT IDENTIFIERs and their more
understandable labels which the \fBdump\fP program (cg/tools/dump) and
the dump facility within the casn library (cg/casn/casn_dump.c) can
use to make the display of object identifiers more comprehensible.
\fBmake_oidtable\fP searches the header file(s) specified on the
command line and writes its output to \fItablefile\fP.


.PP
To make the table, go to cg/asn and issue the command:
.IP
 ../tools/make_oidtable oidtable *.h
.PP
This creates a sorted table of all the identifiers and their labels.
To make use of this table, set your environment variable thus:
.IP
export OIDTABLE=$RPKI_ROOT/cg/asn/oidtable
.PP
Then whenever you run \fBdump -a\fP or \fBdump_smart\fP,
it will label every object identifier that it recognizes like this:
.IP
seq oid 2.5.29.14 /* id_subjectKeyIdentifier */
.PP
The same thing will happen if you use the dump capability within the
casn library.  See various ".raw" files in the \fItestcases\fP
directory.

.SH AUTHOR

Charlie Gardiner.

.SH "SEE ALSO"
.BR dump (1),
.BR dump_smart (1)
