.TH SIGN_CERT 1 "2010 Feb 19" "ASN.1 Tools" "ROA-PKI"

.SH NAME
sign_cert \- signs a certificate or a CRL

.SH SYNOPSIS
.B sign_cert
.I tobesignedfile keyfile

.SH DESCRIPTION
The 
.I tobesignedfile
is signed using the private key in 
.IR keyfile ,
a ".p15" file with label "label" and password "password" as created by
.BR gen_key (1).
The type of contents in the
.I tobesignedfile
are designated by its suffix:
.B .cer
indicates a certificate, and
.B .crl
indicates a CRL.

.SS Response Messages

.nf
       Usage: TBS filename, Key filename
       Finished OK
       Error in ...
       Couldn't open ...
.fi
where the ellipsis is replaced with specific information.

.SH AUTHOR
Charlie Gardiner.

.SH "SEE ALSO"
.BR add_key_info (1),
.BR gen_key (1)
