#!/bin/sh
# clean the rpki-rtr data out of the database

# set environment variables if not set
THIS_SCRIPT_DIR=$(dirname $0)
. $THIS_SCRIPT_DIR/../envir.setup

echo "delete from rtr_update;" | $RPKI_MYSQL_CMD
echo "delete from rtr_full;" | $RPKI_MYSQL_CMD
echo "delete from rtr_incremental;" | $RPKI_MYSQL_CMD
