all:	casn.dir asn_gen.dir asn.dir

casn.dir:
	cd casn && make

asn_gen.dir:
	cd asn_gen && make

asn.dir:
	cd asn && make

clean:
	cd casn && make clean
	cd asn_gen && make clean
	cd asn && make clean
