#!/bin/bash

# set environment variables if not set
THIS_SCRIPT_DIR=$(dirname $0)
. $THIS_SCRIPT_DIR/../envir.setup

. $THIS_SCRIPT_DIR/test.include

. $RPKI_ROOT/trap_errors

echo About to clear database $RPKI_DB ...

# set up an initial database
run "rcli-x-t-y" ../proto/rcli -x -t $PWD/testcases4_LTA -y     # Rsync's local cache
run "rcli-y-F-MYTA" ../proto/rcli -y -F $PWD/testcases4_LTA/MYTA.cer
run "rcli-y-F-C" ../proto/rcli -y -F $PWD/testcases4_LTA/C.cer  # Normal trust anchor
run "rcli-y-F-LTA" ../proto/rcli -y -F $PWD/testcases4_LTA/LTA/LTA.cer    # Local trust anchor

