#!/bin/sh

# set environment variables if not set
THIS_SCRIPT_DIR=$(dirname $(which $0))
source $THIS_SCRIPT_DIR/../envir.setup

echo "update rpki_manifest set next_upd='2008-07-31' where filename='M111.man';" | $RPKI_MYSQL_CMD
