#!/bin/sh
# clean the rpki-rtr data out of the database

# set environment variables if not set
THIS_SCRIPT_DIR=$(dirname $0)
. $THIS_SCRIPT_DIR/../envir.setup

# Note: the order of these commands is important.

# prevents a new server from starting
echo "TRUNCATE TABLE rtr_session;" | $RPKI_MYSQL_CMD

# makes all queries fail
echo "TRUNCATE TABLE rtr_update;" | $RPKI_MYSQL_CMD

# gets rid of data
echo "TRUNCATE TABLE rtr_full;" | $RPKI_MYSQL_CMD
echo "TRUNCATE TABLE rtr_incremental;" | $RPKI_MYSQL_CMD
