$RPKI_ROOT/run_scripts/initDB.sh
rcli -y -F ../root.cer
rcli -y -f badCert2AKI.cer
# rcli -y -f badCert2ASNum.cer
# rcli -y -f badCert2BasicConstr.cer
# rcli -y -f badCert2Cpol.cer
# rcli -y -f badCert2CRLDP.cer
# rcli -y -f badCert2IPAddr.cer
# rcli -y -f badCert2KeyUsage.cer
# rcli -y -f badCert2SKI.cer
# rcli -y -f badCertAIA2AccessDesc.cer
# rcli -y -f badCertAIA2x.cer
# rcli -y -f badCertAIAAccessLoc.cer
# rcli -y -f badCertAIABadAccess.cer
# rcli -y -f badCertAIACrit.cer
# rcli -y -f badCertAKIHash.cer
# rcli -y -f badCertAKILth.cer
# rcli -y -f badCertBadExtension1.cer
# rcli -y -f badCertBasicConstrNoCA.cer
# rcli -y -f badCertBasicConstrNoCrit.cer
# rcli -y -f badCertBasicConstrPathLth.cer
# rcli -y -f badCertCpol2oid.cer
# rcli -y -f badCertCpolNoCrit.cer
# rcli -y -f badCertCRLDP2DistPt.cer
# rcli -y -f badCertCRLDPCrit.cer
# rcli -y -f badCertCRLDPCrlIssuer.cer
# rcli -y -f badCertCRLDPNoDistPt.cer
# rcli -y -f badCertCRLDPReasons.cer
# rcli -y -f badCertEKU.cer
# rcli -y -f badCertInnerSigAlg.cer
# rcli -y -f badCertIssuer2Seq.cer
# rcli -y -f badCertIssuer2SerNums.cer
# rcli -y -f badCertIssuer2Sets.cer
# rcli -y -f badCertIssuerOID.cer
# rcli -y -f badCertIssuerUtf.cer
# rcli -y -f badCertIssUID.cer
# rcli -y -f badCertKUsageExtra.cer
# rcli -y -f badCertKUsageNoCertSign.cer
# rcli -y -f badCertKUsageNoCrit.cer
# rcli -y -f badCertKUsageNoCRLSign.cer
# rcli -y -f badCertNoAIA.cer
# rcli -y -f badCertNoAKI.cer
# rcli -y -f badCertNoBasicConstr.cer
# rcli -y -f badCertNoCpol.cer
# rcli -y -f badCertNoCRLDP.cer
# rcli -y -f badCertNoKeyUsage.cer
# rcli -y -f badCertNoSIA.cer
# rcli -y -f badCertNoSKI.cer
# rcli -y -f badCertNums
# rcli -y -f badCertOuterSigAlg.cer
# rcli -y -f badCertPubKeyAlg.cer
# rcli -y -f badCertPubKeyExp.cer
# rcli -y -f badCertPubKeyLth.cer
# rcli -y -f badCertResourcesASNoCrit.cer
# rcli -y -f badCertResourcesBadAFI.cer
# rcli -y -f badCertResourcesBadASOrder.cer
# rcli -y -f badCertResourcesBadV4Order.cer
# rcli -y -f badCertResourcesBadV6Order.cer
# rcli -y -f badCertResourcesIPNoCrit.cer
# rcli -y -f badCertResourcesNone.cer
# rcli -y -f badCertResourcesSAFI.cer
# rcli -y -f badCertSerNum.cer
# rcli -y -f badCertSIA2x.cer
# rcli -y -f badCertSIAAccessLoc.cer
# rcli -y -f badCertSIAAccessMethod.cer
# rcli -y -f badCertSIAMissing.cer
# rcli -y -f badCertSKIHash.cer
# rcli -y -f badCertSKILth.cer
# rcli -y -f badCertSubject2Seq.cer
# rcli -y -f badCertSubject2SerNum.cer
# rcli -y -f badCertSubject2Sets.cer
# rcli -y -f badCertSubjectOID.cer
# rcli -y -f badCertSubjectUtf.cer
# rcli -y -f badCertSubjUID.cer
# rcli -y -f badCertValCrossed.cer
# rcli -y -f badCertValFromFuture.cer
# rcli -y -f badCertValFromTyp.cer
# rcli -y -f badCertValToPast.cer
# rcli -y -f badCertValToTyp.cer
# rcli -y -f badCertVersion1.cer
# rcli -y -f badCertVersion2.cer
# rcli -y -f badCertVersion4.cer
# rcli -y -f badCertVersionNeg.cer
