#!/bin/sh -e

# NOTE: make_test_cert currently copies the CRLDP from the parent cert.
# This is problematic because TAs must not have CRLDPs.
# To work around this, there are two versions of the TA, one for basing the
# child certs on and one for adding to the database.

cd `dirname "$0"`
. ../../../etc/envir.setup

# first assemble the root cert from source
cp C.fake-parent.orig C.raw
rr < C.raw > C.cer

                                ./make_test_cert C 20000207115900Z 20150313120100Z <makeC
./make_test_cert CM1     0D 1M
./make_test_cert C1      0D 1Y <makeC1
./make_test_cert C1M1    0D 1M
./make_test_cert C11     0D 1Y <makeC11
./make_test_cert C11R1   0D 1M
./make_test_cert C11M1   0D 1M
./make_test_cert C11M2   0D 1M
./make_test_cert C111    0D 1Y <makeC111
./make_test_cert C111R1  0D 1M
./make_test_cert C111R2  0D 1M
./make_test_cert C111R3  0D 1M
./make_test_cert C111M1  0D 1M
./make_test_cert C1111   0D 1Y <makeC1111
./make_test_cert C1111R1 0D 1M
./make_test_cert C112    0D 1Y <makeC112
./make_test_cert C112R1  0D 1M
./make_test_cert C113    0D 1Y <makeC113
./make_test_cert C113R1  0D 1M
./make_test_cert C12     0D 1Y <makeC12
./make_test_cert C121    0D 1Y <makeC121
./make_test_cert C121R1  0D 1M
./make_test_cert C13     0D 1Y <makeC13
./make_test_cert C131    0D 1Y <makeC131
./make_test_cert C131R1  0D 1M
./make_test_cert C132    0D 1Y <makeC132
./make_test_cert C132R1  0D 1M
./make_test_cert C132R2  0D 1M
./make_test_cert C2      0D 1Y <makeC2
./make_test_cert C21     0D 1Y <makeC21
./make_test_cert C211    0D 1Y <makeC211
./make_test_cert C211R1  0D 1M
./make_test_cert C22     0D 1Y <makeC22
./make_test_cert C22R1   0D 1M
./make_test_cert C221    0D 1Y <makeC221
./make_test_cert C221R1  0D 1M
./make_test_cert C2211   0D 1Y <makeC2211
./make_test_cert C2211R1 0D 1M
./make_test_cert C2212   0D 1Y <makeC2212
./make_test_cert C2212R1 0D 1M
./make_test_cert C2212R2 0D 1M
./make_test_cert C23     0D 1Y b <makeC23
./make_test_cert C23R1   0D 1M 
./make_test_cert C23R2   0D 1M n
./make_test_cert C23M1   0D 1M e
./make_test_cert C231    0D 1Y <makeC231
./make_test_cert C231R1  0D 1M
./make_test_cert C231R2  0D 1M
./make_test_cert C232    0D 1Y <makeC232
./make_test_cert C232R1  0D 1M
./make_test_cert C233    0D 1Y <makeC233
./make_test_cert C233R1  0D 1M
./make_test_cert C233R9  0D 1M x

cp C2.cer C2X.cer
cp C2.raw C2X.raw

cp C.real.orig C.raw
rr < C.raw > C.cer
./make_test_cert C 20000207115900Z 20150313120100Z <makeC
